#!/bin/sh

ln_f()
{
    src=$1
    dest=$2
    DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

    if [ -e $dest ] ; then
        backup_dir=~/dotfiles_backup/$(date +"%Y%m%d%H%M%S")
        mkdir -p $backup_dir
        mv $dest $backup_dir/`basename "$dest"`
    fi
    ln -sfn $DIR/$src $dest
}

ln_f .vim ~/.vim
ln_f .vimrc ~/.vimrc
ln_f .bashrc ~/.bashrc
ln_f .tmuxconf ~/.tmuxconf
ln_f config ~/.ssh/config
