#!/bin/sh

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
backup_dir=$DIR/backup/$(date +"%Y%m%d%H%M%S")

ln_f()
{
    src=$1
    dest=$2

    if [ -e $dest ] ; then
        mkdir -p $backup_dir
        mv $dest $backup_dir/`basename "$dest"`
    fi
    ln -sfn $DIR/$src $dest
}

ln_f vim ~/.vim
ln_f vimrc ~/.vimrc
ln_f bashrc ~/.bashrc
ln_f tmux.conf ~/.tmux.conf
ln_f config ~/.ssh/config
ln_f hgrc ~/.hgrc
